### ISSUE TITLE
muy buen trabajo

### ISSUE THREAD

**Issue by ricardoalmira89** [marcovega/colombia-json#1]
quedo perfecto, gracias por el aporte.

**Comment by marcovega** [comment]
Gracias! :D

**Comment by ricardoalmira89** [comment]
te puedo sugerir incluirle las imagenes de las banderas y los escudos de
cada departamento y ciudad, una vez comence a hacerlo pero lo perdi. si
quieres mejorarlo, claro.
saludos.

2015-11-17 14:51 GMT-05:00 Marco Vega <notifications@github.com>:

**Comment by marcovega** [comment]
Conoces alguna forma de conseguirlos de forma muy dinámica y estandarizada? Intentaré hacerlo luego para 2.0, me tocará revisar Wikipedia a ver cómo puedo sacar todo estandarizado.

**Comment by welectronic** [comment]
No es necesario llegar tan lejos, es posible tener los vectores de cada bandera o la url para consumirlos: [https://commons.wikimedia.org/wiki/File:Flag_of_Amazonas_(Colombia).svg](url)
